### ISSUE TITLE
Use let's encrypt certificat

### ISSUE THREAD

**Issue by doudouhightech** [yaroslav-gwit/freebsd-wordpress-autoinstaller#2]
First of all, thank you very much for your script, it works very well for me.

I would like to use let's encrypt with my domain name but I don't want to make any mistake.

As your script is for beginners, I think it would be a good idea to give explanations for using let's encrypt.

But this is just a suggestion, if it's not possible for you, it's already very good.

And if you could just give me some tips on how to do it the best way, that would be nice.

thanks

**Comment by yaroslav-gwit** [comment]
I don't support LE in this setup, because it's supposed to be running behind a reverse proxy. An easy one to manage would be Caddy or Nginx Proxy Manager.

Sorry if it's not much help, but the original design for this script was simply different. I hope you'll understand.
